site_name: Thought Box
site_description: Life on the Pareto Frontier
site_url: https://blog.jnbrymn.com
site_author: John Berryman

theme:
  name: material
  icon:
    logo:material/brain
  favicon: material/brain
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - blog:
      blog_dir: .
      post_dir: blog/posts
      authors_file: .authors.yml
      post_excerpt: required

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - tables
  - footnotes
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/JnBrymn
    - icon: fontawesome/brands/github
      link: https://github.com/JnBrymn

nav:
  - Home: index.md
  - About: about.md
